package client.scenes;

import client.Main;
import commons.Event;

import javafx.geometry.Insets;
import javafx.geometry.Pos;
import javafx.scene.Scene;
import javafx.scene.control.Button;
import javafx.scene.control.Label;
import javafx.scene.control.TextArea;
import javafx.scene.layout.VBox;
import javafx.scene.text.Font;
import javafx.scene.text.FontWeight;
import javafx.scene.text.Text;
import javafx.stage.Modality;
import javafx.stage.Stage;

public class Invitations {
    private Scene scene;
    private TextArea boxToPutEmails;
    private Main main; // reference to Main class
    private Event event;

    /**
     * Getter for the scene
     * @return the scene
     */
    public Scene getScene() {
        return scene;
    }

    /**
     * Constructor for the invitation that calls the method to create the scene
     * @param main scene of the main class
     */
    public Invitations(Main main, Event event) {
        this.main = main;
        this.event = event;
        if(event == null) createSceneNoEvent();
        else createSceneInvitation();
    }

    /**
     * Creates the scene for if there is no event found
     */
    private void createSceneNoEvent() {
        VBox layout = new VBox(5);
        Text noEventText = new Text("No event found");
        layout.getChildren().add(noEventText);
        scene = new Scene(layout, 350, 380);
    }

    /**
     * Creates the GUI for the invitation
     */
    public void createSceneInvitation() {
        // Title of the invitation (hardcoded)
        Text title = new Text("New Year Party");
        title.setFont(Font.font("Arial", FontWeight.BOLD , 20));

        // Invite code (should be generated by the server)
        String placeHolderInviteCode = "AC74ED";

        // Labels for the invite code and the email addresses
        Label inviteCode = new Label("Give people the following Invite Code: "
                + placeHolderInviteCode);
        Label inviteByEmailAddress = new Label("Invite the following people " +
                "by email (one address per line):");

        // text area for email addresses
        boxToPutEmails = new TextArea();
        boxToPutEmails.setPromptText("Enter email addresses here");
        boxToPutEmails.setMaxWidth(350);
        boxToPutEmails.setMaxHeight(100);

        // send invites button (not functional)
        Button sendInvitesButton = new Button("Send Invites");
        sendInvitesButton.setFont(Font.font("Arial"));
        sendInvitesButton.setOnAction(e -> {
            // send the invites to the email addresses in the box
            System.out.println("Invites sent to: " + boxToPutEmails.getText());
        });

        // Back button
        Button backButton = new Button("Back");
        backButton.setOnAction(e -> main.getPrimaryStage().setScene(main.getMainScene()));

        // layout
        VBox layout = new VBox();
        layout.setSpacing(10);
        layout.setPadding(new Insets(20, 20, 20, 20));
        layout.getChildren().addAll(title, inviteCode, inviteByEmailAddress,
                boxToPutEmails, sendInvitesButton, backButton);
        layout.setAlignment(Pos.CENTER);

        scene = new Scene(layout, 270, 300);

        layout.prefWidthProperty().bind(scene.widthProperty());
        layout.prefHeightProperty().bind(scene.heightProperty());
    }

    /**
     * Displays a modal alert box for the Invitations page.
     */
    public void displayAlertBox() {
        Stage window = new Stage();
        window.initModality(Modality.APPLICATION_MODAL);
        window.setTitle("Send Invite");
        window.setScene(scene);
        window.showAndWait();
    }
}
